version: '3.8'
services:
  java-maven-app:
    image: saad324/saad-docker:1.2.1
    ports:
      - 8080:8080
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd
